---
title: Blur
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:year-:month-:day-:title/"
paginate: 10
markdown: kramdown
encoding: utf-8
author:
  name: ZFJ
  email: 421444710@qq.com
  link: https://github.com/ZFJxxx
  github: https://github.com/ZFJxxx
description: 我想看看这个世界
url: https://github.com/ZFJxxx
repo: https://github.com/ZFJxxx/ZFJxxx.github.io
rss: "/pages/atom.xml"
gavatar: http://p7lixluhf.bkt.clouddn.com/%E5%A4%B4%E5%83%8F.jpg
favicon: http://p7lixluhf.bkt.clouddn.com/favicon.ico
ga:
  id: UA-74789926-1
  url: https://github.com/ZFJxxx
disqus:
  shortname: gotoshare
active: tags
cates:
- React
- 摄影
locals:
  ideas: 想法
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  search: 搜索
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll/tagging
- jekyll-tagging-related_posts
- jekyll-seo-tag
- jekyll-mermaid
exclude:
- ".idea/"
- ".github/"
- ".travis/"
- node_modules/
- themes/

