---
title: Blur
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:year-:month-:day-:title/"
paginate: 10
markdown: kramdown
encoding: utf-8
author:
  name: ZFJ
  email:421444710@qq.com
  link: https://ZFJxxx.github.io
  weibo: https://weibo.com/liqing215
  github: https://github.com/ZFJxxx
  zhihu: https://www.zhihu.com/people/JimmyLv
  juejin: https://juejin.im/user/5628752900b07a1836200154
  stackoverflow: https://stackoverflow.com/users/5871340/jimmylv
description: 我想看看这个世界
url: https://blog.jimmylv.info
repo: https://github.com/JimmyLv/jimmylv.github.io
rss: "/pages/atom.xml"
gavatar: http://p7lixluhf.bkt.clouddn.com/%E5%A4%B4%E5%83%8F.jpg
favicon: https://o7mw3gkkh.qnssl.com/blog/public/img/favicon.ico
ga:
  id: UA-74789926-1
  url: https://ZFJxxx.github.io
disqus:
  shortname: gotoshare
active: Java
cates:
- React
- 摄影
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  search: 搜索
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll/tagging
- jekyll-tagging-related_posts
- jekyll-seo-tag
- jekyll-mermaid
exclude:
- ".github/"
- ".travis/"
- node_modules/
- themes/

